spring.application.name=tweet-audit

archive.tweets-path=src/main/resources/sample/tweets.js
x.username=marvee
output.csv-path=output/flagged_tweets.csv
checkpoint.path = output/checkpoint.txt

audit.criteria.forbidden-words=crypto,NFT,hustlegrindset
audit.criteria.professional-check=true
audit.criteria.tone=respectful and thoughtful
audit.criteria.exclude-politics=true

gemini.api-key=${GEMINI_API_KEY:}
gemini.model=gemini-1.5-flash